services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"

  supertokens:
    image: supertokens/supertokens-mongodb:latest
    environment:
      ENABLED_CDI_VERSIONS: '2.7'
      SUPERTOKENS_IN_MEMORY: 'true'
    ports:
      - "3567:3567"
    depends_on:
      - mongo 

volumes:
  mongo-data:
  supertokens-data: